apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-rollouts-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
- apiGroups: ["argoproj.io"]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["create", "get", "update", "delete", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-cluster-access
subjects:
- kind: ServiceAccount
  name: argo-rollouts
  namespace: argocd
roleRef:
  kind: ClusterRole
  name: argo-rollouts-cluster-role
  apiGroup: rbac.authorization.k8s.io
